### ISSUE TITLE
no company tag

### ISSUE THREAD

**Issue by charitasri** [ssavi-ict/LeetCode-Which-Company#331]
unable to find the company tag ..please resolve this issue asap

**Comment by ssavi-ict** [comment]
Hi... Can you share the problem name?

**Comment by charitasri** [comment]
Yes every single problem

**Comment by ssavi-ict** [comment]
Sorry to Hear that. I have checked on my side. Everything is working fine. You can check company information from https://ssavi-ict.github.io/LeetCode-Which-Company/ URL as well.

Can you please share the following information - 

Can you access and see the contents of the following links from your browser: 
1. https://raw.githubusercontent.com/ssavi-ict/LeetCode-Which-Company/main/data/company_info.json
2. https://raw.githubusercontent.com/ssavi-ict/LeetCode-Which-Company/main/data/contests.json
3. https://leetcode.com/api/problems/algorithms/

Also, go to **Chrome Browser > Manage Extensions > Navigate to  CrackTech - Find LeetCode Company Tags extension > Click on the Extension icon** ( it should show " This is a Non-LeetCode Website. "). If you see any button saying "Errors" in the following red-marked area, please click on that button. Let me know if you find any errors.

Could you share some screenshots of the errors you have encountered for better debugging the scenarios?

**Comment by ssavi-ict** [comment]
No further replies for a month. Closing the issues.
