### ISSUE TITLE
Issue: MissSpelled 'Leetcode' to 'Neetcode' under 'Completion Summary' block.

### ISSUE THREAD

**Issue by nishikant23** [ssavi-ict/LeetCode-Which-Company#427]
**Miss Spelled**

![neetcode_webpage](https://github.com/ssavi-ict/LeetCode-Which-Company/assets/119045534/a77dd321-250f-4a5e-a02b-f6f7fe7aad06)

**In code base**

![neetcode](https://github.com/ssavi-ict/LeetCode-Which-Company/assets/119045534/165a344a-d957-434f-91f7-d562ff66f68b)

**Steps to correct**
-[https://github.com/ssavi-ict/LeetCode-Which-Company/blob/main/chrome/leetcoder.html](url) file from where it can be change.

(I corrected the issue in your cloned repo in my system, But while creating PR ->> permission denied showing me.)

**Comment by ssavi-ict** [comment]
It is **NeetCode SDE Sheet**. For your reference, https://neetcode.io/practice
